// SET location
export const SET_LOCATION = 'SET_LOCATION';

// FETCH 'A' restaurant
export const FETCH_RESTAURANT_REQUEST = 'FETCH_RESTAURANT_REQUEST';
export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS';
export const FETCH_RESTAURANT_ERRORS = 'FETCH_RESTAURANT_ERRORS';

// FETCH ALL restaurants
export const FETCH_ALL_RESTAURANTS_REQUEST = 'FETCH_ALL_RESTAURANTS_REQUEST';
export const FETCH_ALL_RESTAURANTS_SUCCESS = 'FETCH_ALL_RESTAURANTS_SUCCESS';
export const FETCH_ALL_RESTAURANTS_ERRORS = 'FETCH_ALL_RESTAURANTS_ERRORS';

// FETCH BY LOCATION restaurants
export const FETCH_RESTAURANTS_BY_LOCATION_REQUEST = 'FETCH_RESTAURANTS_BY_LOCATION_REQUEST';
export const FETCH_RESTAURANTS_BY_LOCATION_SUCCESS = 'FETCH_RESTAURANTS_BY_LOCATION_SUCCESS';
export const FETCH_RESTAURANTS_BY_LOCATION_ERRORS = 'FETCH_RESTAURANTS_BY_LOCATION_ERRORS';

// FETCH 'A' food
export const FETCH_FOOD_REQUEST = 'FETCH_FOOD_REQUEST';
export const FETCH_FOOD_SUCCESS = 'FETCH_FOOD_SUCCESS';
export const FETCH_FOOD_ERRORS = 'FETCH_FOOD_ERRORS';

// FETCH BY RESTAURANT food
export const FETCH_FOOD_BY_RESTAURANT_REQUEST = 'FETCH_FOOD_BY_RESTAURANT_REQUEST';
export const FETCH_FOOD_BY_RESTAURANT_SUCCESS = 'FETCH_FOOD_BY_RESTAURANT_SUCCESS';
export const FETCH_FOOD_BY_RESTAURANT_ERRORS = 'FETCH_FOOD_BY_RESTAURANT_ERRORS';

// FETCH ENTITY BY SEARCH
export const FETCH_ENTITY_BY_SEARCH_REQUEST = 'FETCH_ENTITY_BY_SEARCH_REQUEST';
export const FETCH_ENTITY_BY_SEARCH_SUCCESS = 'FETCH_ENTITY_BY_SEARCH_SUCCESS';
export const FETCH_ENTITY_BY_SEARCH_ERRORS = 'FETCH_ENTITY_BY_SEARCH_ERRORS';

// Cart Constants

// ADD TO cart
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_ERRORS = 'ADD_TO_CART_ERRORS';

// FETCH cart
export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_ERRORS = 'FETCH_CART_ERRORS';

// DELETE FROM cart
export const DELETE_FROM_CART_REQUEST = 'DELETE_FROM_CART_REQUEST';
export const DELETE_FROM_CART_SUCCESS = 'DELETE_FROM_CART_SUCCESS';
export const DELETE_FROM_CART_ERRORS = 'DELETE_FROM_CART_ERRORS';

// SAVE ADDRESS TO cart
export const SAVE_ADDRESS_TO_CART = 'SAVE_ADDRESS_TO_CART';

// SAVE PAYMENT METHOD TO cart
export const SAVE_PAYMENT_METHOD_TO_CART = 'SAVE_PAYMENT_METHOD_TO_CART';