// PLACE order
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_ERRORS = 'PLACE_ORDER_ERRORS';

// ORDER DETAILS
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_ERRORS = 'ORDER_DETAILS_ERRORS';

// FETCH MY orders
export const FETCH_MY_ORDERS_REQUEST = 'FETCH_MY_ORDERS_REQUEST';
export const FETCH_MY_ORDERS_SUCCESS = 'FETCH_MY_ORDERS_SUCCESS';
export const FETCH_MY_ORDERS_ERRORS = 'FETCH_MY_ORDERS_ERRORS';